# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbe5c912e183a2b8bf792da929127559328bd098d31bf0a0df44a79c4e1ad4156ad05463984b572b3c22b79eb479e4bf73099a1ac6005bcbef65c8eb3d4acefb

staging:
  secret_key_base: 58c682036e82e3fff8d3cc239a970244e520c35aa18169c4372908f5a3adbcd71c2af014599409f221d514031fda2c7cd04d451cd357b3ae065c5a1c8df2a5cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
